# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc50f664492a58a0b4698767da40a65c8c56b7eed5fd815b333ef6e533ccefaf03fb48bd87ac096db4d65cead4965483c7017c594de27fc8234394c61274c005

test:
  secret_key_base: a0fe9fff17136d304a2fbcc978b785b420f68616cfa19a9ad83ae9dad9f0be5cffe5635e8029443f33abf836716cc1c279487d911bfc1e482cfa8130a6acabcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
